// src/components/Projects.tsx
import React from 'react';
import { ExternalLink, Github } from 'lucide-react';
import { useData } from '../context/DataContext';
import '../styles/projects.css';

const Projects: React.FC = () => {
  const { projects } = useData();

  return (
    <section id="projects" className="projects">
      <div className="projects-container">
        <div className="projects-header">
          <p className="projects-subtitle">Browse My Recent</p>
          <h2 className="projects-title">Projects</h2>
        </div>

        <div className="projects-grid">
          {projects.map((project, index) => (
            <div
              key={index}
              className="project-card"
            >
              {/* Project Image */}
              <div className="project-image-container">
                <img
                  src={project.image}
                  alt={project.title}
                  className="project-image"
                />
              </div>

              {/* Project Content */}
              <div className="project-content">
                <h3 className="project-title">
                  {project.title}
                </h3>
                <p className="project-description">
                  {project.description}
                </p>

                {/* Technologies */}
                <div className="project-technologies">
                  {project.technologies.map((tech, techIndex) => (
                    <span
                      key={techIndex}
                      className="project-tech-tag"
                    >
                      {tech}
                    </span>
                  ))}
                </div>

                {/* Action Buttons */}
                <div className="project-actions">
                  <a
                    href={project.githubUrl}
                    className="project-btn project-btn-secondary"
                  >
                    <Github className="w-4 h-4 mr-2" />
                    Github
                  </a>
                  <a
                    href={project.liveUrl}
                    className="project-btn project-btn-primary"
                  >
                    <ExternalLink className="w-4 h-4 mr-2" />
                    Live Demo
                  </a>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default Projects;

// src/app/components/projects/projects.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LucideAngularModule, ExternalLink, Github } from 'lucide-angular';
import { DataService } from '../../services/data.service';

@Component({
  selector: 'app-projects',
  standalone: true,
  imports: [CommonModule, LucideAngularModule],
  template: `
    <section id="projects" class="projects">
      <div class="projects-container">
        <div class="projects-header">
          <p class="projects-subtitle">Browse My Recent</p>
          <h2 class="projects-title">Projects</h2>
        </div>

        <div class="projects-grid">
          <div
            *ngFor="let project of dataService.projects$ | async"
            class="project-card"
          >
            <!-- Project Image -->
            <div class="project-image-container">
              <img
                [src]="project.image"
                [alt]="project.title"
                class="project-image"
              />
            </div>

            <!-- Project Content -->
            <div class="project-content">
              <h3 class="project-title">
                {{ project.title }}
              </h3>
              <p class="project-description">
                {{ project.description }}
              </p>

              <!-- Technologies -->
              <div class="project-technologies">
                <span
                  *ngFor="let tech of project.technologies"
                  class="project-tech-tag"
                >
                  {{ tech }}
                </span>
              </div>

              <!-- Action Buttons -->
              <div class="project-actions">
                <a
                  [href]="project.githubUrl"
                  class="project-btn project-btn-secondary"
                >
                  <lucide-icon [img]="Github" class="w-4 h-4 mr-2"></lucide-icon>
                  Github
                </a>
                <a
                  [href]="project.liveUrl"
                  class="project-btn project-btn-primary"
                >
                  <lucide-icon [img]="ExternalLink" class="w-4 h-4 mr-2"></lucide-icon>
                  Live Demo
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  `,
  styleUrls: ['./projects.component.css']
})
export class ProjectsComponent {
  readonly ExternalLink = ExternalLink;
  readonly Github = Github;

  constructor(public dataService: DataService) {}
}
