// src/components/admin/Login.tsx
import React, { useState } from 'react';
import { useAuth } from '../../context/AuthContext';
import { useNavigate } from 'react-router-dom';
import { Lock, Mail, Eye, EyeOff } from 'lucide-react';
import '../../styles/admin.css';

const Login: React.FC = () => {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [showPassword, setShowPassword] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState('');
  const { login } = useAuth();
  const navigate = useNavigate();

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsLoading(true);
    setError('');

    try {
      const success = await login(email, password);
      if (success) {
        navigate('/admin');
      } else {
        setError('Invalid email or password');
      }
    } catch (err) {
      setError('An error occurred. Please try again.');
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="login-container">
      <div className="login-card">
        <div className="login-header">
          <div className="login-icon">
            <Lock />
          </div>
          <h1 className="login-title">Admin Login</h1>
          <p className="login-subtitle">Sign in to manage your portfolio</p>
        </div>

        <div className="login-demo-info">
          <p>
            <strong>Demo Credentials:</strong><br />
            Email: admin@portfolio.com<br />
            Password: admin123
          </p>
        </div>

        <form onSubmit={handleSubmit} className="login-form">
          <div className="form-group">
            <label htmlFor="email" className="form-label">
              Email Address
            </label>
            <div className="login-form-group">
              <Mail />
              <input
                type="email"
                id="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                required
                className="login-form-input"
                placeholder="Enter your email"
              />
            </div>
          </div>

          <div className="form-group">
            <label htmlFor="password" className="form-label">
              Password
            </label>
            <div className="login-form-group">
              <Lock />
              <input
                type={showPassword ? 'text' : 'password'}
                id="password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                required
                className="login-form-input"
                placeholder="Enter your password"
              />
              <button
                type="button"
                onClick={() => setShowPassword(!showPassword)}
                className="login-password-toggle"
              >
                {showPassword ? <EyeOff /> : <Eye />}
              </button>
            </div>
          </div>

          {error && (
            <div className="alert alert-error">
              <p>{error}</p>
            </div>
          )}

          <button
            type="submit"
            disabled={isLoading}
            className="login-submit"
          >
            {isLoading ? 'Signing in...' : 'Sign In'}
          </button>
        </form>

        <div className="login-back-link">
          <a
            href="/"
          >
            ← Back to Portfolio
          </a>
        </div>
      </div>
    </div>
  );
};

export default Login;

// src/app/pages/login/login.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { LucideAngularModule, Lock, Mail, Eye, EyeOff } from 'lucide-angular';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, FormsModule, LucideAngularModule],
  template: `
    <div class="login-container">
      <div class="login-card">
        <div class="login-header">
          <div class="login-icon">
            <lucide-icon [img]="Lock"></lucide-icon>
          </div>
          <h1 class="login-title">Admin Login</h1>
          <p class="login-subtitle">Sign in to manage your portfolio</p>
        </div>

        <div class="login-demo-info">
          <p>
            <strong>Demo Credentials:</strong><br />
            Email: admin@portfolio.com<br />
            Password: admin123
          </p>
        </div>

        <form (ngSubmit)="onSubmit()" #loginForm="ngForm" class="login-form">
          <div class="form-group">
            <label for="email" class="form-label">
              Email Address
            </label>
            <div class="login-form-group">
              <lucide-icon [img]="Mail"></lucide-icon>
              <input
                type="email"
                id="email"
                name="email"
                [(ngModel)]="email"
                required
                class="login-form-input"
                placeholder="Enter your email"
              />
            </div>
          </div>

          <div class="form-group">
            <label for="password" class="form-label">
              Password
            </label>
            <div class="login-form-group">
              <lucide-icon [img]="Lock"></lucide-icon>
              <input
                [type]="showPassword ? 'text' : 'password'"
                id="password"
                name="password"
                [(ngModel)]="password"
                required
                class="login-form-input"
                placeholder="Enter your password"
              />
              <button
                type="button"
                (click)="togglePassword()"
                class="login-password-toggle"
              >
                <lucide-icon [img]="showPassword ? EyeOff : Eye"></lucide-icon>
              </button>
            </div>
          </div>

          <div *ngIf="error" class="alert alert-error">
            <p>{{ error }}</p>
          </div>

          <button
            type="submit"
            [disabled]="isLoading || !loginForm.form.valid"
            class="login-submit"
          >
            {{ isLoading ? 'Signing in...' : 'Sign In' }}
          </button>
        </form>

        <div class="login-back-link">
          <a routerLink="/">
            ← Back to Portfolio
          </a>
        </div>
      </div>
    </div>
  `,
  styleUrls: ['./login.component.css']
})
export class LoginComponent {
  readonly Lock = Lock;
  readonly Mail = Mail;
  readonly Eye = Eye;
  readonly EyeOff = EyeOff;

  email = '';
  password = '';
  showPassword = false;
  isLoading = false;
  error = '';

  constructor(
    private authService: AuthService,
    private router: Router
  ) {}

  togglePassword() {
    this.showPassword = !this.showPassword;
  }

  async onSubmit() {
    this.isLoading = true;
    this.error = '';

    try {
      const success = await this.authService.login(this.email, this.password);
      if (success) {
        this.router.navigate(['/admin']);
      } else {
        this.error = 'Invalid email or password';
      }
    } catch (err) {
      this.error = 'An error occurred. Please try again.';
    } finally {
      this.isLoading = false;
    }
  }
}
